from . import views
from django.urls import path

urlpatterns = [
    path('', views.login_view, name='entrance'),
    path('portfolio/', views.home, name='home'),
    path('hobby/', views.hobby, name='hobby'),
    path("save-changes/", views.save_changes, name="save_changes"),
    path("upload-profile-image/", views.upload_profile_image, name="upload_profile_image"),
    path('api/hobbies/save/', views.save_hobbies, name='save_hobbies'),
    path('api/hobbies/get/', views.get_hobbies, name='get_hobbies'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('patient-dashboard/', views.patient_dashboard, name='patient_dashboard'),
    path('book-appointment/', views.book_appointment, name='book_appointment'),
    path('medical-history/', views.medical_history, name='medical_history'),
    path('find-doctor/', views.find_doctor, name='find_doctor'),
    path('cancel-appointment/<int:appointment_id>/', views.cancel_appointment, name='cancel_appointment'),
    path('delete-appointment/<int:appointment_id>/', views.delete_appointment, name='delete_appointment'),
    path('medical-records/', views.medical_records, name='medical_records'),
    path('prescriptions/', views.prescriptions, name='prescriptions'),
    path('payments/', views.payments, name='payments'),
    path('notifications/', views.notifications, name='notifications'),
    path('profile-settings/', views.profile_settings, name='profile_settings'),
    path('help-support/', views.help_support, name='help_support'),
    path('notifications/mark-read/<int:notification_id>/', views.mark_notification_read, name='mark_notification_read'),
    path('notifications/mark-all-read/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('notifications/delete/<int:notification_id>/', views.delete_notification, name='delete_notification'),
    path('appointments/<int:appointment_id>/', views.appointment_detail, name='appointment_detail'),
    path('prescriptions/download/<int:prescription_id>/', views.download_prescription, name='download_prescription'),
    path('prescriptions/view/<int:prescription_id>/', views.view_prescription, name='view_prescription'),
    path('doctor-dashboard/', views.doctor_dashboard, name='doctor_dashboard'),
    path('doctor/appointments/', views.doctor_appointments, name='doctor_appointments'),
    path('doctor/patients/', views.doctor_patients, name='doctor_patients'),
    path('doctor/complete-appointment/<int:appointment_id>/', views.complete_appointment, name='complete_appointment'),
    path('doctor/cancel-appointment/<int:appointment_id>/', views.doctor_cancel_appointment, name='doctor_cancel_appointment'),
    path('doctor/delete-appointment/<int:appointment_id>/', views.doctor_delete_appointment, name='doctor_delete_appointment'),
    path('doctor/patient/<int:patient_id>/', views.doctor_patient_detail, name='doctor_patient_detail'),
    path('doctor/medical-records/', views.doctor_medical_records, name='doctor_medical_records'),
    path('doctor/notifications/', views.doctor_notifications, name='doctor_notifications'),
    path('doctor/settings/', views.doctor_settings, name='doctor_settings'),
    path('doctor/medical-record/<int:record_id>/', views.view_medical_record, name='view_medical_record'),
    path('doctor/medical-record/<int:record_id>/delete/', views.delete_medical_record, name='delete_medical_record'),
    path('doctor/accept-appointment/<int:appointment_id>/', views.accept_appointment, name='accept_appointment'),
]