# Generated by Django 5.1.6 on 2025-02-18 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_userprofile_allergies_userprofile_blood_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('APPOINTMENT', 'Appointment'), ('MEDICAL_RECORD', 'Medical Record'), ('PRESCRIPTION', 'Prescription'), ('SYSTEM', 'System Message')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_link', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myApp.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
