# Generated by Django 5.1.6 on 2025-04-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_doctorregistrationcode'),
        ('myApp', 'add_prc_license'),
    ]

    operations = [
    ]
