# Generated by Django 5.1.6 on 2025-04-21 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_merge_0007_doctorregistrationcode_add_prc_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='prc_license',
            field=models.CharField(blank=True, help_text='Professional Regulation Commission License Number', max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_type', models.CharField(choices=[('CONFINEMENT', 'Confinement'), ('SPECIALIST', 'Specialist Consultation'), ('TESTS', 'Medical Tests'), ('OTHER', 'Other')], default='CONFINEMENT', max_length=20)),
                ('severity_level', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CRITICAL', 'Critical')], default='MODERATE', max_length=20)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('date_referred', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=200)),
                ('hospital_address', models.TextField(blank=True)),
                ('expected_duration', models.CharField(blank=True, max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='myApp.userprofile')),
                ('referring_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='myApp.doctor')),
            ],
            options={
                'ordering': ['-date_referred'],
            },
        ),
    ]
